### PR TITLE
Fix typo while checking success

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by pksunkara** [comment]
And please release a new version after this is merged.

**Comment by opichals** [comment]
@amanjain97 Would be nice to get this patched. Without this the orb reports failures for successful CI runs.

**Review by opichals — APPROVED** [review]
Looks good!

**Comment by amanjain97** [comment]
Hi. @pksunkara @opichals 
Thanks for the fix. I shall make a new release tomorrow and will notify you soon.

**Comment by kuba-kubula** [comment]
@amanjain97 Thanks for the promising release

**Comment by amanjain97** [comment]
@kuba-kubula @pksunkara Can you please verify the change from v0.1.3

**Comment by kuba-kubula** [comment]
@amanjain97 🤦 Hi, I see the code you've released as new version is the same as 0.1.2 = the problematic one.

Please can you release the latest `master` as a new version the sooner the better? Thanks.

**Comment by amanjain97** [comment]
Hi @kuba-kubula I have published in v0.1.5
I was mistakenly uploading old package. Please let me know if you need any other improvements.
If you have a lot of improvements then I can give you a publisher role. 🙇‍♂️

**Comment by amanjain97** [comment]
Hi @kuba-kubula I have published in v0.1.5
I was mistakenly uploading old package. Please let me know if you need any other improvements.
If you have a lot of improvements then I can give you additional roles in this repository.

**Pull request merged**
